### ISSUE TITLE
Add ability to get counts from endpints

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/STNServices#1]
Request from Todd:
>Per this morning's conversation, here is a list of endpoints where it would be really handy to add a "Count=True" parameter so that the web service would just respond with a count, rather than with the entire data set:

- [ ] Sensor > Filtered Sensors
- [ ] HWM > Filtered HWMs
- [ ] HWM > Approval HWMs
- [ ] Site > Filtered Sites
- [ ] Peak Summary > Filtered Peak Summaries

**Comment by lprivette** [comment]
related to https://github.com/USGS-WiM/STNServices/issues/1

**Comment by HansVraga** [comment]
Closing in favor of #127
