### ISSUE TITLE
Setup static IPs

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/STNServices#15]
Need to be able to hookup a test client to the new services

**Comment by HansVraga** [comment]
Probaby a "me" issue, but are static IPs necessary for a domain name in Fargate? Feels like a blast from the past a bit. I assume the need here is an address for us to reliably point to for the services?

**Comment by lprivette** [comment]
yes that's the need. Dan's going to reach out to J in a bit for more info on how this is done

**Comment by lprivette** [comment]
test

**Comment by lprivette** [comment]
test

**Comment by lprivette** [comment]
test

**Comment by DanielJBeckman** [comment]
Static IP complete. Process recorded but not documented by Patrick.
