### ISSUE TITLE
Setting up .netcore on Linux; unable to run exectutable due to apparent permissions issue.

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/STNServices#9]
I'm following these guide doc to setup .netcore on our new Linux server: 
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-apache?view=aspnetcore-2.1&tabs=aspnetcore2x

The guide is using CentOS 7 instead of Ubuntu 16.04, but .netcore is [compatible with that distro of linux](https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x). So I've been following the guide using Ubuntu 16.04 instead of CentOS 7. The only differences I've encountered so far were command syntax. 

I completed all the steps down to where it says "Start the service and verify that it's running:". Here I run into an apparent permissions error (see image below, commands made are highlighted yellow):
![image](https://user-images.githubusercontent.com/23640741/43534201-ced08036-9584-11e8-8321-fe8acbc161ad.png)

It is failing at the dotnet executable. So I checked the permissions for that file:
![image](https://user-images.githubusercontent.com/23640741/43534290-f7167dac-9584-11e8-8d3c-d940faf28904.png)

First of all, there's the `x` in each group, which would imply that I should be able to run it, right? 
Second, I tried running this command to open it up to everyone, just to see if that fixed it:  
![image](https://user-images.githubusercontent.com/23640741/43534352-27691bae-9585-11e8-9738-f527e0c329b5.png)

It says that it's updated the file to 777 but if you look at the file again, it still `-rwxr-xr-x` which is wrong if it's been changed to 777 right? It should be `rwxrwxrwx`.

Ever encountered a permissions issue like that? Where it should be updated but it's not? 

And/or is there a way for me to somehow run `sudo` for the `ExecStart` section within that service file (image of file contents below):
![image](https://user-images.githubusercontent.com/23640741/43529896-4aa4dd34-957a-11e8-87e2-d042c95833b5.png)

Any ideas? @jknewson @aaronstephenson

**Comment by aaronstephenson** [comment]
Hi @lprivette I just now have time available to help. Let's chat IRL when you're in the office.

**Comment by aaronstephenson** [comment]
@lprivette It looks like it's working to me...
![image](https://user-images.githubusercontent.com/8713712/43858345-6767834c-9b13-11e8-8627-45c397d7fae6.png)
![image](https://user-images.githubusercontent.com/8713712/43858364-738c029c-9b13-11e8-8fc3-54db60544f08.png)

It seems you just didn't restart this kestrel service after changing the permissions on the dotnet file.

I would recommend scaling back the permissions now to determine the exact minimum settings that will work; you don't want to leave the 'other' permissions wide open. Perhaps start by returning the permissions back to their initial settings (755).

**Comment by lprivette** [comment]
Can't seem to connect at all today. Is it possible that the internal IP changed?

**Comment by HansVraga** [comment]
Going to close, if further issues occur, will open a new one.
